global:
  scrape_interval: 5s
  external_labels:
    site: prod

remote_write:
  - url: "http://victoriametrics:8428/api/v1/write"
    queue_config:
      max_samples_per_send: 10000

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: ['alertmanager:9093']

rule_files:
  -  'rules.yml'

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: alertmanager
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: grafana
    static_configs:
      - targets: ['grafana:3000']

  - job_name: victoriametrics
    static_configs:
      - targets: ['victoriametrics:8428']

  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: mysql
    static_configs:
      - targets: ['mysql-exporter:9104']

  - job_name: nginx
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://www.ya.ru
        - http://172.17.0.1:8080/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
