global:
  scrape_interval: 5s

scrape_configs:

  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: mysql
    scrape_interval: 5s
    static_configs:
    - targets: ['mysql-exporter:9104']

  - job_name: nginx
    metrics_path: /nginx_status
    scrape_interval: 5s
    static_configs:
    - targets: ['nginx-exporter:9113']

  - job_name: wordpress
    scrape_interval: 5s
    static_configs:
    - targets: ['wordpress-exporter:11011']

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://www.ya.ru
        - http://172.17.0.1:8080/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
