version: '3.5'

services:
  elasticsearch:
    image: elasticsearch:7.16.1
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "password"
      discovery.type: single-node
    restart: unless-stopped
    networks:
      - elk
    ports:
      - 9200:9200
      - 9300:9300

  logstash:
    image: logstash:7.16.2
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    restart: unless-stopped
    ports:
      - 5044:5044
      - 5000:5000
      - 9600:9600
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.16.1
    hostname: kibana
    container_name: kibana
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    restart: unless-stopped
    networks:
      - elk
    ports:
      - 5601:5601

networks:
  elk:
    driver: bridge
