version: '3.5'

services:

  postgres-server:
    image: postgres:latest
    hostname: postgres
    container_name: postgres-server
    restart: unless-stopped
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      PG_DATA: /var/lib/postgresql/data/pgdata
    networks: 
      default:
        ipv4_address: 172.28.0.6

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-latest
    hostname: zabbix-server
    container_name: zabbix-server
    restart: unless-stopped
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbixNew
      ZBX_HISTORYSTORAGETYPES: log,text
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
    depends_on:
      - postgres-server
    ports:
      - 10051:10051
    extra_hosts:
      - "zabbix-server:172.28.0.2"   # хотел для удобства захода в вебку, но так агент нормально съел коннекшн с сервером
    networks: 
      default:
        ipv4_address: 172.28.0.2
    volumes:
      - /usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-latest
    hostname: zabbix-web
    container_name: zabbix-web
    restart: unless-stopped
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbixNew
      ZBX_SERVER_HOST: zabbix-server
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "Asia/Kolkata"  
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - postgres-server
      - zabbix-server
    ports:
      - 8090:80
      - 8443:8443
    extra_hosts:
      - "zabbix-web:172.28.0.4"
    networks: 
      default:
        ipv4_address: 172.28.0.4

  zabbix-agent:   # Zabbix agent service that tracks usage and send to zabbix server
    image: zabbix/zabbix-agent:latest
    hostname: zabbix-agent   #по запарке оставил имя агента, но работает и ладно, хостнейм в данном случае не принципиален
    container_name: zabbix-agent
    privileged: true   #access mode for allowing resource access
    restart: unless-stopped
    links:
      - zabbix-server:zabbix-server
    depends_on:
      - zabbix-server
    networks: 
      default:
        ipv4_address: 172.28.0.3
    ports: 
      - 10050:10050
    environment:
      - ZBX_SERVER_HOST=zabbix-server #the IP/Dns of Zabbix server

networks:
  default:
    ipam:
      config:
        - subnet: 172.28.0.0/16   #забиндил айпишники для удобства после перезагрузок докера
